'use client'

import { View, Text, Image, Link, StyleSheet } from '@react-pdf/renderer'

const ZLOG_URL = 'https://zlog.app'

/**
 * Fixed PDF page header — full-width branded accent bar on every page.
 * brandColor / logoUrl come from the report's selected company branding.
 */
export function PdfHeader({
  brandColor = '#FF5000',
  logoUrl = null,
  companyName = '',
  reportTitle = '',
}) {
  const color = brandColor || '#FF5000'

  const styles = StyleSheet.create({
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 64,
      backgroundColor: color,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 28,
      paddingVertical: 10,
    },
    logo: {
      width: 40,
      height: 40,
      objectFit: 'contain',
      marginRight: 12,
    },
    textBlock: {
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'center',
    },
    company: {
      color: '#FFFFFF',
      fontSize: 11,
      fontFamily: 'Helvetica-Bold',
      letterSpacing: 0.4,
    },
    title: {
      color: '#FFFFFF',
      fontSize: 9,
      marginTop: 2,
      opacity: 0.92,
      fontFamily: 'Helvetica',
    },
  })

  return (
    <View style={styles.header} fixed>
      {logoUrl ? (
        // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image
        <Image src={logoUrl} style={styles.logo} />
      ) : null}
      <View style={styles.textBlock}>
        {companyName ? <Text style={styles.company}>{companyName}</Text> : null}
        {reportTitle ? <Text style={styles.title}>{reportTitle}</Text> : null}
      </View>
    </View>
  )
}

/**
 * Fixed PDF page footer — centered page count, Zlog credit, thin branded closing bar.
 */
export function PdfFooter({ brandColor = '#FF5000' }) {
  const color = brandColor || '#FF5000'

  const styles = StyleSheet.create({
    wrap: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
    },
    content: {
      height: 30,
      paddingHorizontal: 28,
      position: 'relative',
      justifyContent: 'center',
    },
    brandLink: {
      position: 'absolute',
      left: 28,
      top: 8,
      fontSize: 7.5,
      color: color,
      fontFamily: 'Helvetica',
      textDecoration: 'underline',
    },
    pageText: {
      fontSize: 8,
      color: '#444',
      fontFamily: 'Helvetica',
      textAlign: 'center',
    },
    accentBar: {
      height: 5,
      backgroundColor: color,
      width: '100%',
    },
  })

  return (
    <View style={styles.wrap} fixed>
      <View style={styles.content}>
        <Link src={ZLOG_URL}>
          <Text style={styles.brandLink}>Report generated by Zlog</Text>
        </Link>
        <Text
          style={styles.pageText}
          render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
        />
      </View>
      <View style={styles.accentBar} />
    </View>
  )
}

/** Vertical space reserved under the fixed header on document body pages */
export const PDF_HEADER_OFFSET = 72

/** Vertical space reserved above the fixed footer */
export const PDF_FOOTER_OFFSET = 42
